# SPDX-License-Identifier: GPL-3.0-or-later
"""Render previews of a hash-pinned generated scene without executing scripts.

This is deliberately separate from GLB finishing. The coordinator must enqueue
only source.blend artifacts generated by the trusted finishing worker; the
scene marker is a consistency check, not a signature for arbitrary .blend files.
"""
from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path
import sys
import time
import traceback
from datetime import datetime, timezone

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))
import bpy
from audit import artifact, blender_filename, filesystem_path, prepare_output, read_bounded, read_preview_parameters
from worker import emit, render_previews, stage, texture_stats, write_json

SOURCE_LIMIT = 256 * 1024 * 1024
PREVIEW_NAMES = ("thumbnail.png",) + tuple(f"turntable-{i:02d}.png" for i in range(4))


def verify_generated_scene():
    if len(bpy.data.scenes) != 1:
        raise ValueError("Preview requires one generated quality scene")
    scene = bpy.context.scene
    if scene.get("assetStudioGeneratedScene") != "quality-worker-v2" or scene.get("assetStudioPipelineVersion") != 2:
        raise ValueError("Preview input is not a current generated quality-worker scene")
    if bpy.data.texts or bpy.data.libraries or bpy.data.cache_files:
        raise ValueError("Generated preview scene contains text, linked libraries or external caches")
    for prop in bpy.data.bl_rna.properties:
        if prop.type != "COLLECTION":
            continue
        for block in getattr(bpy.data, prop.identifier):
            animation = getattr(block, "animation_data", None)
            if animation and animation.drivers:
                raise ValueError("Generated preview scene contains animation drivers")
            tree = getattr(block, "node_tree", None)
            animation = getattr(tree, "animation_data", None)
            if animation and animation.drivers:
                raise ValueError("Generated preview node tree contains animation drivers")
    for image in bpy.data.images:
        if image.source in {"MOVIE", "SEQUENCE"} or (image.source == "FILE" and not image.packed_file):
            raise ValueError("Generated preview scene contains an unpacked/external image")
        if max(image.size, default=0) > 8192:
            raise ValueError("Generated preview texture exceeds the native image bound")
    for font in bpy.data.fonts:
        if font.filepath != "<builtin>" and not font.packed_file:
            raise ValueError("Generated preview scene contains an external font")
    if not 1 <= len(bpy.data.objects) <= 64 or len(bpy.data.images) > 64:
        raise ValueError("Generated preview scene exceeds its object/image bound")
    camera = scene.camera
    if camera is None or camera.type != "CAMERA" or not camera.get("assetStudioThumbnailLocation"):
        raise ValueError("Generated preview scene lacks its fixed preview camera")
    game = [obj for obj in scene.objects if obj.get("assetStudioRole") == "game"]
    if len(game) != 1 or game[0].type != "MESH":
        raise ValueError("Generated preview scene lacks its one fixed game mesh")
    height = scene.get("assetStudioHeightMeters")
    size = scene.get("assetStudioModelSizeMeters")
    if (not isinstance(height, (int, float)) or isinstance(height, bool) or not math.isfinite(height)
            or not 0.03 <= height <= 100 or not isinstance(size, (int, float)) or isinstance(size, bool)
            or not math.isfinite(size) or not 0 < size <= 100000):
        raise ValueError("Generated preview scene has invalid fixed camera dimensions")
    return scene, camera, float(height), float(size)


def execute(input_path, output_dir):
    started = time.monotonic()
    if not bpy.app.background or "--disable-autoexec" not in sys.argv or "--factory-startup" not in sys.argv:
        raise ValueError("Preview worker requires --background --factory-startup --disable-autoexec")
    bpy.context.preferences.filepaths.use_scripts_auto_execute = False
    job = read_preview_parameters(input_path)
    source_path = filesystem_path(job["sourcePath"])
    data = read_bounded(source_path, SOURCE_LIMIT)
    if hashlib.sha256(data).hexdigest() != job["sourceSha256"].lower():
        raise ValueError("Generated scene SHA-256 differs from preview job")
    output = prepare_output(output_dir)
    # Import from a new private immutable snapshot, closing the hash-to-open race.
    snapshot = output / ".preview-source.blend"
    with snapshot.open("xb") as stream:
        stream.write(data)
    stage("open-generated-scene")
    bpy.ops.wm.open_mainfile(filepath=blender_filename(snapshot), load_ui=False, use_scripts=False)
    bpy.context.preferences.filepaths.use_scripts_auto_execute = False
    _, camera, height, size = verify_generated_scene()
    stage("render-preview", requestedMode=job["previewMode"])
    rendered = render_previews(output, camera, height, size, job["previewMode"])
    measurements = {}
    for name in PREVIEW_NAMES:
        image = bpy.data.images.load(blender_filename(output / name), check_existing=False)
        image.colorspace_settings.name = "sRGB"
        measured = texture_stats(image)
        expected = (1024, 1024) if name == "thumbnail.png" else (512, 512)
        if tuple(image.size) != expected or measured["sampleDistinctRGB8"] < 16:
            raise ValueError("Preview pixels did not pass fixed dimensions/non-solid image checks")
        measurements[name] = measured
        bpy.data.images.remove(image)
    if hashlib.sha256(read_bounded(source_path, SOURCE_LIMIT)).hexdigest() != job["sourceSha256"].lower():
        raise ValueError("Original generated scene changed during preview rendering")
    report = {"schemaVersion": 2, "valid": True, "createdAt": datetime.now(timezone.utc).isoformat(),
              "name": job["name"], "blenderVersion": bpy.app.version_string,
              "sourceSha256": job["sourceSha256"].lower(), "originalSourcePreserved": True,
              "generatedSceneMarker": "quality-worker-v2", "scriptAutoExecution": False,
              "textBlocks": 0, "drivers": 0, "linkedLibraries": 0, "externalResources": 0,
              "preview": rendered, "imageMeasurements": measurements,
              "elapsedSeconds": round(time.monotonic() - started, 3)}
    write_json(output / "preview-validation.json", report)
    files = [artifact(output / name, "thumbnail") for name in PREVIEW_NAMES]
    files.append(artifact(output / "preview-validation.json", "metadata"))
    for item in files:
        emit("artifact", **item)
    emit("completed", artifacts=files, validation=report)


def main():
    parser = argparse.ArgumentParser(description="Fixed generated-scene preview worker")
    parser.add_argument("--input", required=True)
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args(sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else [])
    try:
        execute(args.input, args.output_dir)
    except Exception as exc:
        emit("failed", stage="preview", error=str(exc), errorType=type(exc).__name__)
        traceback.print_exc(file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
