[workspace]
members = ["crates/core", "crates/scheduler", "crates/providers", "crates/image-pipeline", "apps/desktop/src-tauri"]
resolver = "2"

[workspace.package]
version = "0.1.11"
edition = "2021"
license = "Apache-2.0"

[profile.dev]
debug = 0

[profile.release]
lto = "thin"
strip = true
codegen-units = 8
