import {useCallback, useEffect, useMemo, useRef, useState} from 'react';
import type {FormEvent, PointerEvent as ReactPointerEvent} from 'react';
import {Box, ChevronDown, ChevronRight, CircleHelp, Columns2, Copy, Download, FileImage, FilePlus2, Folder, FolderOpen, Grid2X2, Image, Layers, ListFilter, Maximize2, Minus, MoreHorizontal, MousePointer2, Package, Paintbrush, Play, Plus, RefreshCw, RotateCcw, Search, Settings2, SlidersHorizontal, Sparkles, Square, Upload, X, Check, AlertTriangle, Clock3, CheckCircle2, Ban, LoaderCircle, PanelLeftClose, Palette, Link2, Eraser, Circle, ExternalLink} from 'lucide-react';
import {DEFAULT_SPEC, DEFAULT_STYLE, EXPORT_PRESETS} from '@local-assets/contracts';
import type {Asset, AssetSpec, AssetVersion, EnvironmentInfo, ImageOperation, Job, ModelParameters, ProjectSnapshot, ProviderConnection, StyleGuide} from '@local-assets/contracts';
import {artifactUrl, bootstrap, chooseFolder, chooseImports, command, environment, importFiles, isNative, providerLogin, providerStatus} from './lib/bridge';
import {subscribeBrowser} from './lib/browser';
import {messages, shortcutModifier, type Locale} from './lib/i18n';
import ModelViewport from './components/ModelViewport';
import {BookOpen} from 'lucide-react';
import AppUpdatePanel from './components/AppUpdatePanel';
import UsageGuide from './components/UsageGuide';
import CodexSetupPanel from './components/CodexSetupPanel';
import {useAppUpdater} from './lib/useAppUpdater';

type View = 'library' | 'canvas' | 'model' | 'compare';
type Dialog = 'project'|'model'|'atlas'|'split'|'export'|'plan'|'generate'|'provider'|'environment'|'update'|'guide'|'job'|null;
type Inspector = 'asset'|'spec'|'style';
const ACTIVE = new Set(['pending','ready','running','retry_wait']);
const JOB_LABELS:Record<string,string> = {pending:'대기',ready:'실행 가능',running:'실행 중',retry_wait:'재시도 대기',waiting_user:'사용자 확인',succeeded:'완료',failed:'실패',cancelled:'취소',external_unknown:'결과 불명'};
const DOMAIN_LABELS:Record<string,string> = {game:'게임',design:'웹 · 앱 디자인',product:'제품 시각화',architecture:'건축 · 인테리어',education:'교육 · 시뮬레이션'};
const KIND_LABELS:Record<string,string> = {image:'이미지',texture:'텍스처',sprite:'스프라이트',model:'3D 모델'};
const EMPTY_ASSETS:Asset[] = [];
const UNIT_FACTORS = {m:1,cm:.01,mm:.001};
const scaledValue = (value:number,factor:number)=>Number((value*factor).toPrecision(12));
const meters = (parameters:ModelParameters,unit:AssetSpec['unit']):ModelParameters => ({...parameters,width:parameters.width*UNIT_FACTORS[unit],depth:parameters.depth*UNIT_FACTORS[unit],height:parameters.height*UNIT_FACTORS[unit],bevel:parameters.bevel*UNIT_FACTORS[unit]});
const bytes = (n:number) => n > 1048576 ? `${(n/1048576).toFixed(1)} MB` : `${Math.max(1,Math.round(n/1024))} KB`;
const getVersion = (asset:Asset) => asset.versions.find(v=>v.id === asset.activeVersionId) ?? asset.versions.at(-1)!;
const outputArtifact = (version:AssetVersion|undefined) => version?.artifacts.find(a=>a.role === 'output' && ['png','webp','jpeg','jpg','gif','glb','gltf'].includes(a.format.toLowerCase())) ?? version?.artifacts.find(a=>a.role === 'source');
const thumbnailArtifact = (asset:Asset) => getVersion(asset)?.artifacts.find(a=>a.role === 'thumbnail') ?? getVersion(asset)?.artifacts.find(a=>['png','webp','jpeg','jpg','gif','bmp'].includes(a.format.toLowerCase()));
const formatTime = (value:string|null) => value ? new Date(value).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}) : '—';

function IconButton({title,children,onClick,active=false,disabled=false}:{title:string;children:React.ReactNode;onClick?:()=>void;active?:boolean;disabled?:boolean}) {
  return <button className={`icon-button ${active?'active':''}`} title={title} aria-label={title} onClick={onClick} disabled={disabled}>{children}</button>;
}
function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}) {
  return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;
}
function NumberField({label,value,onChange,min=0,max=16384,step=1}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number|'any'}) {
  return <Field label={label}><input type="number" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></Field>;
}
function StatusIcon({status}:{status:string}) {
  return status==='succeeded'?<CheckCircle2 size={14}/>:status==='failed'||status==='external_unknown'?<AlertTriangle size={14}/>:status==='cancelled'?<Ban size={14}/>:status==='running'?<LoaderCircle className="spin" size={14}/>:<Clock3 size={14}/>;
}
function ProviderPanel({connection,checking,busy,onCheck,onLogin,receivedCount,validatedCount,confirmedModels}:{connection:ProviderConnection|null;checking:'status'|'login'|null;busy:boolean;onCheck:()=>void;onLogin:()=>void;receivedCount:number;validatedCount:number;confirmedModels:string[]}) {
  const confirmedModel=connection?.confirmedModel??(confirmedModels.length?confirmedModels.join(', '):null);
  const usage=connection?.usage;
  const hasUsage=Array.isArray(usage)?usage.length>0:!!usage&&typeof usage==='object'&&Object.keys(usage).length>0;
  return <section className="provider-card provider-connection" aria-label="GPT Image2 연결 정보">
    <div><strong>GPT Image2 · 공식 런타임</strong><span className={`status-tag ${isNative&&connection?.ready?'ready':'blocked'}`}>{!isNative?'데스크톱 전용':connection?.ready?'연결 준비':connection?'연결 확인 필요':'미확인'}</span></div>
    <p>{!isNative?'이미지 생성 연동은 데스크톱에서 확인하세요.':connection?.ready?'연결이 준비됐습니다. 생성 성공은 수신 이미지에서 확인합니다.':'계정 연결과 실행 상태를 먼저 확인하세요.'}</p>
    <CodexSetupPanel connection={connection} checking={checking} busy={busy} onCheck={onCheck} onLogin={onLogin}/>
    <dl className="property-list">
      <div><dt>추론 모델</dt><dd>{connection?.reasoningModel??'확인되지 않음'}</dd></div>
      <div><dt>모델 이용 권한</dt><dd>확인되지 않음</dd></div>
      <div><dt>요청 모델</dt><dd>{connection?.requestedModel??'gpt-image-2'}</dd></div>
      <div><dt>이 프로젝트의 수신 파일</dt><dd>{receivedCount}개 / 파일 검증 {validatedCount}개</dd></div>
    </dl>
    <p className="provider-proof-brief">{receivedCount?'수신 파일 검증과 응답 모델 확인을 따로 기록합니다.':'이 프로젝트에 수신된 이미지가 없습니다.'}</p>
    <details className="provider-details"><summary>연결·검증 상세</summary>
      <p>{connection?.reason??(isNative?'공식 런타임과 구독 인증을 확인한 뒤 요청을 제출할 수 있습니다.':'브라우저에서는 공식 생성 요청과 인증을 실행할 수 없습니다.')}</p>
      <dl className="property-list">
        <div><dt>런타임</dt><dd>{connection?.runtimeVersion??(isNative?'확인 필요':'사용할 수 없음')}</dd></div>
        <div><dt>인증</dt><dd>{connection?.authenticated?'공식 런타임 인증됨':isNative?'확인 필요':'데스크톱에서 연결'}</dd></div>
        <div><dt>확인된 응답 모델</dt><dd>{confirmedModel??'확인되지 않음'}</dd></div>
        <div><dt>사용 한도</dt><dd>{hasUsage?'공식 런타임에서 정보 수신':'확인 필요'}</dd></div>
        {connection&&<div><dt>연결 확인 시각</dt><dd>{formatTime(connection.checkedAt)}</dd></div>}
      </dl>
      <p className="provider-proof-note">{connection?.catalogSource==='application_pinned_catalog'?'추론 모델 이름은 앱에 고정된 모델 목록 기준입니다. ':''}연결 준비는 모델 이용 권한이나 실제 생성 성공을 확인한 상태가 아닙니다. 실제 생성 지원은 이미지 수신 후 확인하며, 파일 검증과 응답 모델 확인은 별도로 기록합니다.</p>
    </details>
  </section>;
}

export default function App() {
  const [snapshot,setSnapshot] = useState<ProjectSnapshot|null>(null);
  const [env,setEnv] = useState<EnvironmentInfo|null>(null);
  const [locale,setLocale] = useState<Locale>('ko');
  const t = messages[locale];
  const [error,setError] = useState('');
  const [notice,setNotice] = useState('');
  const [busy,setBusy] = useState(false);
  const [view,setView] = useState<View>('library');
  const [inspector,setInspector] = useState<Inspector>('asset');
  const [selectedIds,setSelectedIds] = useState<string[]>([]);
  const [query,setQuery] = useState('');
  const [kind,setKind] = useState('all');
  const [folder,setFolder] = useState('all');
  const [tag,setTag] = useState('');
  const [dialog,setDialog] = useState<Dialog>(null);
  const [jobDetail,setJobDetail] = useState<Job|null>(null);
  const [projectName,setProjectName] = useState('새 에셋 프로젝트');
  const [spec,setSpec] = useState<AssetSpec>({...DEFAULT_SPEC});
  const [style,setStyle] = useState<StyleGuide>({...DEFAULT_STYLE});
  const [assetName,setAssetName] = useState('');
  const [assetTags,setAssetTags] = useState('');
  const [prompt,setPrompt] = useState('');
  const [planApproved,setPlanApproved] = useState(true);
  const [connection,setConnection] = useState<ProviderConnection|null>(null);
  const [providerChecking,setProviderChecking] = useState<'status'|'login'|null>(null);
  const [generationPrompt,setGenerationPrompt] = useState('');
  const [generationName,setGenerationName] = useState('');
  const [generationCount,setGenerationCount] = useState(1);
  const [generationApproved,setGenerationApproved] = useState(false);
  const [model,setModel] = useState<ModelParameters>({template:'crate',name:'나무 상자',width:1,depth:1,height:1,color:'#b39674',bevel:.035});
  const [modelCount,setModelCount] = useState(1);
  const [atlas,setAtlas] = useState({width:2048,height:2048,padding:4});
  const [split,setSplit] = useState({width:64,height:64});
  const [spriteFrameRate,setSpriteFrameRate] = useState(12);
  const [exportPreset,setExportPreset] = useState('game');
  const [exportFormat,setExportFormat] = useState('png');
  const [zoom,setZoom] = useState(.8);
  const [grid,setGrid] = useState(false);
  const [pivot,setPivot] = useState(true);
  const [repeat,setRepeat] = useState(false);
  const [wireframe,setWireframe] = useState(false);
  const [brush,setBrush] = useState<'select'|'erase'|'restore'>('select');
  const [radius,setRadius] = useState(20);
  const [maskPoints,setMaskPoints] = useState<[number,number][]>([]);
  const [drawing,setDrawing] = useState(false);
  const [resize,setResize] = useState({width:512,height:512});
  const [crop,setCrop] = useState({x:0,y:0,width:256,height:256});
  const [color,setColor] = useState({hue:0,saturation:1});
  const [background,setBackground] = useState({color:'#ffffff',tolerance:30});
  const [compareA,setCompareA] = useState('');
  const [compareB,setCompareB] = useState('');
  const [comparePosition,setComparePosition] = useState(50);
  const [queueFilter,setQueueFilter] = useState('all');
  const [queueOpen,setQueueOpen] = useState(true);
  const [dragging,setDragging] = useState(false);
  const [recent,setRecent] = useState<{name:string;root:string}[]>(()=>{try{return JSON.parse(localStorage.getItem('asset-workbench-recent')??'[]');}catch{return [];}});
  const fileInput = useRef<HTMLInputElement>(null);
  const searchInput = useRef<HTMLInputElement>(null);
  const imageStageRef = useRef<HTMLDivElement>(null);
  const brushMoved = useRef(false);
  const providerCheckingRef = useRef(false);
  const generationSubmitting = useRef(false);
  const modelInputUnit = useRef(spec.unit);
  const project = snapshot?.project;
  const assets = project?.assets??EMPTY_ASSETS;
  const selected = assets.find(a=>a.id===selectedIds[0]);
  const selectedVersion = selected ? getVersion(selected) : undefined;
  const selectedUrl = snapshot ? artifactUrl(snapshot,outputArtifact(selectedVersion)) : '';
  const selectionAssets = assets.filter(a=>selectedIds.includes(a.id));
  const imageAssets = selectionAssets.filter(a=>a.kind!=='model');
  const fitImage = useCallback(()=>{const stage=imageStageRef.current;if(!stage||!selected?.width||!selected.height)return;const bounds=stage.getBoundingClientRect();setZoom(Math.max(.01,Math.min(1,(bounds.width-48)/selected.width,(bounds.height-48)/selected.height)));},[selected?.width,selected?.height]);
  const jobs = project?.jobs??[];
  const receivedImageVersions = assets.flatMap(a=>a.kind==='model'?[]:a.versions.filter(v=>v.source==='codex_subscription'&&v.requestedModel==='gpt-image-2'&&v.artifacts.some(a=>['source','output'].includes(a.role)&&['png','webp','jpg','jpeg'].includes(a.format.toLowerCase())&&a.bytes>0&&/^[a-f0-9]{64}$/i.test(a.sha256))));
  const validatedImageCount = receivedImageVersions.filter(v=>v.validation?.valid).length;
  const confirmedImageModels = [...new Set(receivedImageVersions.map(v=>v.confirmedModel).filter((value):value is string=>!!value))];
  const activeJobs = jobs.filter(j=>ACTIVE.has(j.status));
  const updateWorkBlocked=busy||!snapshot||activeJobs.length>0;
  const updater=useAppUpdater(updateWorkBlocked);
  const folders = [...new Set(assets.map(a=>a.folder))];
  const tags = [...new Set(assets.flatMap(a=>a.tags))];
  const filtered = useMemo(()=>assets.filter(a=>(kind==='all'||a.kind===kind)&&(folder==='all'||a.folder===folder)&&(!tag||a.tags.includes(tag))&&(!query||`${a.name} ${a.tags.join(' ')}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))),[assets,kind,folder,tag,query]);
  const filteredJobs = jobs.filter(j=>queueFilter==='all'||(queueFilter==='active'?ACTIVE.has(j.status):j.status===queueFilter)).slice().reverse();

  const acceptSnapshot = useCallback((next:ProjectSnapshot)=>{
    setSnapshot(next);
    if(isNative) setRecent(prev=>{const items=[{name:next.project.name,root:next.root},...prev.filter(p=>p.root!==next.root)].slice(0,5);localStorage.setItem('asset-workbench-recent',JSON.stringify(items));return items;});
  },[]);
  const run = useCallback(async(request:Record<string,unknown>,message?:string)=>{
    setBusy(true);setError('');
    try {const next = await command(request);acceptSnapshot(next);if(message)setNotice(message);return next;}
    catch(err){setError(err instanceof Error?err.message:String(err));return null;}
    finally {setBusy(false);}
  },[acceptSnapshot]);
  const checkProvider = useCallback(async(login=false)=>{
    if(providerCheckingRef.current)return;
    providerCheckingRef.current=true;setProviderChecking(login?'login':'status');setError('');
    try{const next=await(login?providerLogin():providerStatus());setConnection(next);if(login)setNotice(next.ready?'공식 런타임 연결이 준비되었습니다. 이미지 생성은 직접 제출하세요.':'공식 인증 상태를 확인했습니다. 로그인 완료 후 연결을 다시 확인하세요.');}
    catch(err){setConnection(null);setError(err instanceof Error?err.message:String(err));}
    finally{providerCheckingRef.current=false;setProviderChecking(null);}
  },[]);
  const openGeneration = ()=>{setGenerationApproved(style.approved);setDialog('generate');};
  const providerPanel = <ProviderPanel connection={connection} checking={providerChecking} busy={busy} onCheck={()=>void checkProvider()} onLogin={()=>void checkProvider(true)} receivedCount={receivedImageVersions.length} validatedCount={validatedImageCount} confirmedModels={confirmedImageModels}/>;

  useEffect(()=>{let disposed=false;bootstrap().then(next=>{if(disposed)return;acceptSnapshot(next);setSpec({...next.project.spec});setStyle({...next.project.styleGuide});setSelectedIds(next.project.assets[0]?[next.project.assets[0].id]:[]);}).catch(err=>!disposed&&setError(String(err)));environment().then(info=>!disposed&&setEnv(info)).catch(err=>!disposed&&setError(String(err)));return()=>{disposed=true;};},[acceptSnapshot]);
  useEffect(()=>{if(isNative)return;return subscribeBrowser(()=>{void command({action:'snapshot'}).then(acceptSnapshot).catch(err=>setError(String(err)));});},[acceptSnapshot]);
  useEffect(()=>{if(!isNative||!activeJobs.length)return;let disposed=false;let timeout:ReturnType<typeof setTimeout>;const tick=async()=>{try{const next=await command({action:'snapshot'});if(!disposed)acceptSnapshot(next);}catch(err){if(!disposed)setError(String(err));}if(!disposed)timeout=setTimeout(tick,800);};timeout=setTimeout(tick,300);return()=>{disposed=true;clearTimeout(timeout);};},[activeJobs.length,acceptSnapshot]);
  useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id);},[notice]);
  useEffect(()=>{if(!selected)return;setAssetName(selected.name);setAssetTags(selected.tags.join(', '));setResize({width:selected.width??512,height:selected.height??512});setCrop({x:0,y:0,width:selected.width??256,height:selected.height??256});setMaskPoints([]);setCompareA(selected.versions[0]?.id??'');setCompareB(selected.activeVersionId);},[selected?.id,selected?.activeVersionId]);
  useEffect(()=>{if(view==='canvas')fitImage();},[view,selected?.id,fitImage]);
  useEffect(()=>{setSelectedIds(ids=>{const valid=ids.filter(id=>assets.some(a=>a.id===id));return valid.length===ids.length?ids:valid;});},[assets]);
  useEffect(()=>{if(!dialog)return;const previous=document.activeElement as HTMLElement|null;const panel=document.querySelector<HTMLElement>('.dialog');if(!panel)return;const selector='button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),summary,[tabindex="0"]';const first=panel.querySelector<HTMLElement>('input:not([disabled]),textarea:not([disabled]),select:not([disabled])')??panel.querySelector<HTMLElement>(selector);first?.focus();const trap=(event:KeyboardEvent)=>{if(event.key!=='Tab')return;const items=Array.from(panel.querySelectorAll<HTMLElement>(selector)).filter(el=>el.offsetParent!==null);if(!items.length)return;const first=items[0];const last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);previous?.focus();};},[dialog]);
  useEffect(()=>{if(!project)return;setSpec({...project.spec});setStyle({...project.styleGuide});setExportPreset(EXPORT_PRESETS.find(p=>p.domain===project.spec.domain)?.id??'game');setSelectedIds(project.assets[0]?[project.assets[0].id]:[]);setFolder('all');setTag('');setQuery('');},[project?.id]);
  useEffect(()=>{const previous=modelInputUnit.current;if(previous===spec.unit)return;const factor=UNIT_FACTORS[previous]/UNIT_FACTORS[spec.unit];setModel(current=>({...current,width:scaledValue(current.width,factor),depth:scaledValue(current.depth,factor),height:scaledValue(current.height,factor),bevel:scaledValue(current.bevel,factor)}));modelInputUnit.current=spec.unit;},[spec.unit]);
  useEffect(()=>{if(!isNative)return;let unlisten:(()=>void)|undefined;let stopped=false;import('@tauri-apps/api/webview').then(async({getCurrentWebview})=>{const off=await getCurrentWebview().onDragDropEvent(event=>{if(event.payload.type==='over')setDragging(true);else if(event.payload.type==='leave')setDragging(false);else if(event.payload.type==='drop'){setDragging(false);void run({action:'import',paths:event.payload.paths},'원본을 보존해 프로젝트로 가져왔습니다.');}});if(stopped)off();else unlisten=off;}).catch(err=>setError(String(err)));return()=>{stopped=true;unlisten?.();};},[run]);

  const importAssets = useCallback(async()=>{if(!isNative){fileInput.current?.click();return;}setBusy(true);try{const next=await chooseImports();if(next){acceptSnapshot(next);setNotice('원본을 보존해 프로젝트로 가져왔습니다.');}}catch(err){setError(String(err));}finally{setBusy(false);}},[acceptSnapshot]);
  const openProject = useCallback(async(root?:string)=>{if(!isNative){setNotice('내보낸 프로젝트 ZIP을 선택하세요. 마지막 프로젝트는 이 기기에서 자동 복원됩니다.');fileInput.current?.click();return;}try{const chosen=root??await chooseFolder('프로젝트 폴더 열기');if(chosen){const next=await run({action:'open',root:chosen});if(next){setSpec({...next.project.spec});setStyle({...next.project.styleGuide});setSelectedIds(next.project.assets[0]?[next.project.assets[0].id]:[]);}}}catch(err){setError(String(err));}},[run]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='i'){event.preventDefault();void importAssets();}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='e'){event.preventDefault();setDialog('export');}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='f'){event.preventDefault();searchInput.current?.focus();}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='a'&&event.target instanceof HTMLElement&&!['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName)){event.preventDefault();setSelectedIds(filtered.map(a=>a.id));}if(event.key==='Escape'){setDialog(null);setMaskPoints([]);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[filtered,importAssets]);

  const selectAsset = (asset:Asset,multi=false) => {setSelectedIds(prev=>multi?(prev.includes(asset.id)?prev.filter(id=>id!==asset.id):[...prev,asset.id]):[asset.id]);setInspector('asset');};
  const openAsset = (asset:Asset) => {setSelectedIds([asset.id]);setView(asset.kind==='model'?'model':'canvas');};
  const applyImage = (operation:ImageOperation) => {if(!selected)return;void run({action:'process',assetId:selected.id,operation},'수정본을 새 버전으로 제작합니다.');};
  const newProject = async(event:FormEvent)=>{event.preventDefault();try{let root='browser';if(isNative){const chosen=await chooseFolder('새 프로젝트를 저장할 폴더 선택');if(!chosen)return;root=chosen;}const next=await run({action:'create',root,name:projectName},'새 프로젝트를 만들었습니다.');if(next){setSpec({...next.project.spec});setStyle({...next.project.styleGuide});setSelectedIds([]);setDialog(null);setFolder('all');setTag('');setQuery('');}}catch(err){setError(String(err));}};
  const exportAssets = async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{let destination='downloads';if(isNative){const chosen=await chooseFolder('에셋 묶음을 내보낼 폴더 선택');if(!chosen)return;destination=chosen;}const result=await command<{path:string}>({action:'export',destination,assetIds:selectedIds.length?selectedIds:assets.map(a=>a.id),preset:exportPreset,format:exportFormat});setNotice(`실제 파일과 manifest를 내보냈습니다. ${result.path}`);setDialog(null);}catch(err){setError(String(err));}finally{setBusy(false);}};
  const createModels = async(event:FormEvent)=>{event.preventDefault();if(!Number.isInteger(modelCount)||modelCount<1||modelCount>24){setError('모델 수는 1~24개 사이의 정수로 입력하세요.');return;}const canonical=meters(model,spec.unit);if([canonical.width,canonical.depth,canonical.height].some(v=>v<.03||v>100)){setError('실제 모델 치수는 3cm~100m 사이로 입력하세요.');return;}const models=Array.from({length:modelCount},(_,index)=>({...canonical,name:modelCount>1?`${model.name} ${String(index+1).padStart(2,'0')}`:model.name}));const next=await run({action:'model',models},isNative?'Blender 작업 큐에 모델 제작을 추가했습니다.':'브라우저의 로컬 메시 제작 큐에 추가했습니다.');if(next)setDialog(null);};
  const createImages = async(event:FormEvent)=>{
    event.preventDefault();if(generationSubmitting.current)return;
    if(!isNative){setError('데스크톱 전용: GPT Image2 생성은 공식 런타임을 연결한 Tauri 앱에서 제출하세요.');return;}
    if(!connection?.ready){setError('공식 런타임 연결을 먼저 확인하세요.');return;}
    if(!generationApproved){setError('현재 규격과 스타일을 제작 기준으로 승인하세요.');return;}
    if(!generationPrompt.trim()){setError('제작할 이미지 설명을 입력하세요.');return;}
    if(!Number.isInteger(generationCount)||generationCount<1||generationCount>20){setError('이미지 수는 1~20개 사이의 정수로 입력하세요.');return;}
    generationSubmitting.current=true;setBusy(true);setError('');
    try{
      const approvedStyle={...style,approved:true};
      acceptSnapshot(await command({action:'update',spec,styleGuide:approvedStyle}));setStyle(approvedStyle);
      const next=await command({action:'generate',requestId:crypto.randomUUID(),prompt:generationPrompt.trim(),name:generationName.trim()||undefined,count:generationCount});
      acceptSnapshot(next);setNotice(`GPT Image2 이미지 ${generationCount}개 요청을 작업 큐에 추가했습니다. 수신 결과는 파일과 함께 기록됩니다.`);setDialog(null);
    }catch(err){setError(err instanceof Error?err.message:String(err));}
    finally{generationSubmitting.current=false;setBusy(false);}
  };
  const plan = useMemo(()=>{
    const hasModel=/상자|컨테이너|crate|테이블|책상|table|선반|shelf|3d|3D/.test(prompt);
    const template:ModelParameters['template']=/테이블|책상|table/.test(prompt)?'table':/선반|shelf/.test(prompt)?'shelf':'crate';
    const modelMatch=prompt.match(/(?:상자|컨테이너|crate|테이블|책상|table|선반|shelf)(?:\s*3[Dd])?(?:\s*모델)?\s*(\d+)\s*개/)??prompt.match(/(?:3[Dd]\s*모델|모델)\s*(\d+)\s*개/)??prompt.match(/(?:crate|table|shelf)\s*(\d+)\b/);
    const iconMatch=prompt.match(/(?:아이콘|이미지|icon|image)\s*(\d+)\s*(?:개)?/);
    return {hasModel,template,models:hasModel?Number(modelMatch?.[1]??1):0,images:/아이콘|이미지|image|icon|배경|일러스트/.test(prompt)?Number(iconMatch?.[1]??1):0};
  },[prompt]);
  const runPlan = async()=>{
    if(generationSubmitting.current)return;
    if(!planApproved){setError('스타일 가이드를 승인해야 제작을 시작할 수 있습니다.');return;}
    if(plan.models<0||plan.models>24||plan.images<0||plan.images>20){setError('한 계획의 모델은 최대 24개, 이미지는 최대 20개입니다. 요청 수를 조정하세요.');return;}
    if(!plan.models&&!plan.images){setError('제작할 이미지 또는 로컬 모델을 설명하세요.');return;}
    if(plan.images&&isNative&&!connection?.ready){setError('이미지 제작에 사용할 공식 런타임 연결을 먼저 확인하세요.');return;}
    if(plan.images&&!isNative&&!plan.models){setDialog('provider');return;}
    const canonical=meters(model,spec.unit);
    if(plan.models&&[canonical.width,canonical.depth,canonical.height].some(v=>!Number.isFinite(v)||v<.03||v>100)){setError('실제 모델 치수는 3cm~100m 사이로 입력하세요.');return;}
    generationSubmitting.current=true;setBusy(true);setError('');let queuedModels=false;
    try{
      const approvedStyle={...style,approved:true};
      acceptSnapshot(await command({action:'update',spec,styleGuide:approvedStyle}));setStyle(approvedStyle);
      if(plan.models){
        const name=plan.template==='table'?'테이블':plan.template==='shelf'?'선반':'상자';
        const models=Array.from({length:plan.models},(_,index)=>({...canonical,template:plan.template,name:`${name} ${index+1}`}));
        acceptSnapshot(await command({action:'model',models,prompt}));queuedModels=true;
      }
      if(plan.images&&isNative)acceptSnapshot(await command({action:'generate',requestId:crypto.randomUUID(),prompt:prompt.trim(),name:'제작 계획 이미지',count:plan.images}));
      setNotice(!isNative&&plan.images?`로컬 모델 ${plan.models}개를 큐에 추가했습니다. 이미지 ${plan.images}개는 데스크톱 전용으로 제출되지 않았습니다.`:`제작 계획을 큐에 추가했습니다.${plan.models?` 로컬 모델 ${plan.models}개.`:''}${plan.images?` GPT Image2 이미지 요청 ${plan.images}개.`:''}`);setDialog(null);
    }catch(err){setError(`${queuedModels?'로컬 모델은 큐에 추가되었습니다. 이미지 요청 제출 실패: ':''}${err instanceof Error?err.message:String(err)}`);}
    finally{generationSubmitting.current=false;setBusy(false);}
  };

  const drawMask = (event:ReactPointerEvent<HTMLDivElement>)=>{if(brush==='select'||!selected||!selected.width||!selected.height)return;const rect=event.currentTarget.getBoundingClientRect();const point:[number,number]=[Math.max(0,Math.min(selected.width-1,Math.round((event.clientX-rect.left)/rect.width*selected.width))),Math.max(0,Math.min(selected.height-1,Math.round((event.clientY-rect.top)/rect.height*selected.height)))];setMaskPoints(prev=>prev.length<10000?[...prev,point]:prev);};
  const modelUrl = selected?.kind==='model'?selectedUrl:null;
  const oldVersion = selected?.versions.find(v=>v.id===compareA);
  const newVersion = selected?.versions.find(v=>v.id===compareB);
  const imageSource = (v:AssetVersion|undefined)=>snapshot?artifactUrl(snapshot,outputArtifact(v)):'';

  return <div className={`workbench ${dragging?'dragging':''}`} onDragOver={event=>{if(!isNative&&event.dataTransfer.types.includes('Files')){event.preventDefault();setDragging(true);}}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setDragging(false);}} onDrop={async event=>{if(isNative)return;event.preventDefault();setDragging(false);const files=Array.from(event.dataTransfer.files);if(!files.length)return;setBusy(true);try{acceptSnapshot(await importFiles(files));setNotice(`${files.length}개의 원본 파일을 가져왔습니다.`);}catch(err){setError(String(err));}finally{setBusy(false);}}}>
    <input ref={fileInput} className="sr-only" type="file" multiple accept="image/png,image/jpeg,image/webp,image/gif,image/bmp,.glb,.zip" onChange={async event=>{const files=Array.from(event.target.files??[]);if(!files.length)return;setBusy(true);try{acceptSnapshot(await importFiles(files));setNotice('원본 파일을 로컬 프로젝트에 가져왔습니다.');}catch(err){setError(String(err));}finally{setBusy(false);event.target.value='';}}}/>
    <header className="titlebar">
      <div className="brand"><span className="brand-symbol"><Layers size={21} strokeWidth={1.7}/></span><span>Asset Studio<small>local asset workbench</small></span></div>
      <div className="project-breadcrumb"><Folder size={14}/><button onClick={()=>void openProject()}>{project?.name??'프로젝트 준비 중'}</button><ChevronDown size={12}/><span className="saved-dot" title="프로젝트는 로컬에 저장됩니다"/></div>
      <div className="titlebar-actions"><span className="runtime-badge"><Circle size={6} fill="currentColor"/>{isNative?t.native:t.browser}</span><button className="button quiet guide-button" onClick={()=>setDialog('guide')}><BookOpen size={16}/>사용 가이드</button>{updater.status.state==='available'?<button className="button small app-update-alert" onClick={()=>setDialog('update')}>v{updater.status.latestVersion} 업데이트</button>:<IconButton title="앱 업데이트" onClick={()=>setDialog('update')}><RefreshCw size={16}/></IconButton>}<button className="button quiet" title="공급자 연동 상태" onClick={()=>setDialog('provider')}><Link2 size={16}/>구독 연결</button><IconButton title={t.settings} onClick={()=>setDialog('environment')}><Settings2 size={16}/></IconButton><button className="button primary export-top" onClick={()=>setDialog('export')} disabled={!assets.length}><Download size={14}/>{t.export}<kbd>{shortcutModifier()} E</kbd></button></div>
    </header>

    <aside className="sidebar" aria-label="프로젝트와 에셋 탐색">
      <div className="sidebar-heading"><span>{t.projects}</span><IconButton title="새 프로젝트" onClick={()=>setDialog('project')}><Plus size={15}/></IconButton></div>
      <button className="project-entry" onClick={()=>{setView('library');setFolder('all');setKind('all');setTag('');}}><span className="project-folder"><FolderOpen size={20}/></span><span><strong>{project?.name??'로컬 작업 공간'}</strong><small>{isNative?'프로젝트 폴더': '브라우저 로컬 저장'}</small></span><MoreHorizontal size={15}/></button>
      <button className="sidebar-action" onClick={()=>void openProject()}><FolderOpen size={14}/>프로젝트 열기<kbd>{isNative?'폴더':'복원'}</kbd></button>
      {recent.length>1&&<details className="recent"><summary>{t.recent}</summary>{recent.slice(1).map(item=><button key={item.root} title={item.root} onClick={()=>void openProject(item.root)}><Folder size={12}/>{item.name}</button>)}</details>}
      <div className="sidebar-separator"/>
      <div className="sidebar-heading"><span>라이브러리</span><span className="small-count">{assets.length}</span></div>
      <button className={`nav-item ${folder==='all'&&kind==='all'&&!tag?'active':''}`} onClick={()=>{setFolder('all');setKind('all');setTag('');setView('library');}}><Grid2X2 size={16}/>{t.all}<span>{assets.length}</span></button>
      <button className={`nav-item ${kind==='image'?'active':''}`} onClick={()=>{setKind('image');setFolder('all');setTag('');setView('library');}}><Image size={16}/>2D 이미지<span>{assets.filter(a=>a.kind==='image').length}</span></button>
      <button className={`nav-item ${kind==='model'?'active':''}`} onClick={()=>{setKind('model');setFolder('all');setTag('');setView('library');}}><Box size={16}/>3D 모델<span>{assets.filter(a=>a.kind==='model').length}</span></button>
      <button className={`nav-item ${kind==='sprite'?'active':''}`} onClick={()=>{setKind('sprite');setFolder('all');setTag('');setView('library');}}><Layers size={16}/>스프라이트<span>{assets.filter(a=>a.kind==='sprite').length}</span></button>
      <button className={`nav-item ${kind==='texture'?'active':''}`} onClick={()=>{setKind('texture');setFolder('all');setTag('');setView('library');}}><Square size={16}/>텍스처<span>{assets.filter(a=>a.kind==='texture').length}</span></button>
      <div className="sidebar-heading folder-heading"><span>폴더</span></div>
      {folders.length?folders.map(name=><button key={name} className={`folder-item ${folder===name?'active':''}`} onClick={()=>{setFolder(name);setKind('all');setTag('');setView('library');}}><ChevronRight size={11}/><Folder size={14}/>{name||'에셋'}<span>{assets.filter(a=>a.folder===name).length}</span></button>):<span className="sidebar-empty">파일을 가져오면 폴더가 표시됩니다.</span>}
      <div className="sidebar-heading tag-heading"><span>태그</span></div>
      <div className="tag-list">{tags.slice(0,10).map(name=><button key={name} className={tag===name?'active':''} onClick={()=>{setTag(tag===name?'':name);setView('library');}}><span/> {name}</button>)}{!tags.length&&<span className="sidebar-empty">선택한 에셋에 태그를 추가하세요.</span>}</div>
      <div className="sidebar-separator"/>
      <div className="sidebar-heading"><span>{t.presets}</span><Palette size={14}/></div>
      {EXPORT_PRESETS.map(p=><button key={p.id} className={`preset-entry ${project?.spec.domain===p.domain?'selected':''}`} onClick={()=>{const next={...spec,domain:p.domain,target:p.target,axis:p.axis as AssetSpec['axis'],unit:p.unit as AssetSpec['unit']};setSpec(next);setExportPreset(p.id);setInspector('spec');void run({action:'update',spec:next},`${p.name} 규격을 적용했습니다.`);}}><span className={`preset-dot ${p.id}`}/>{DOMAIN_LABELS[p.domain]}</button>)}
      <div className="sidebar-footer"><div><span className="connection-dot"/>{t.local}</div><button onClick={()=>setDialog('environment')}><CircleHelp size={14}/><span>환경 및 지원 정보</span><ChevronRight size={12}/></button></div>
    </aside>

    <main className="main-workspace">
      <div className="workspace-tabs" role="tablist" aria-label="작업 화면">
        {([{id:'library',label:t.library,Icon:Grid2X2},{id:'canvas',label:t.canvas,Icon:Image},{id:'model',label:t.model,Icon:Box},{id:'compare',label:t.compare,Icon:Columns2}] as const).map(({id,label,Icon})=><button key={id} role="tab" aria-selected={view===id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon size={15}/>{label}</button>)}
        <div className="tab-trailing"><span>{selectedIds.length>0?`${selectedIds.length}개 선택`: `${assets.length}개 에셋`}</span><IconButton title="선택 해제" onClick={()=>setSelectedIds([])} disabled={!selectedIds.length}><X size={13}/></IconButton></div>
      </div>
      {view==='library'&&<>
        <div className="library-heading"><div><div className="location"><FolderOpen size={12}/>{project?.name??'프로젝트'}<ChevronRight size={11}/>{folder==='all'?'라이브러리':folder}</div><h1>{tag?`#${tag}`:kind!=='all'?KIND_LABELS[kind]:folder!=='all'?folder:'에셋 라이브러리'}</h1><p>원본을 보존하고, 필요한 결과만 다시 제작하세요.</p></div><button className="button" onClick={()=>void importAssets()} disabled={busy}><Upload size={14}/>{t.import}<kbd>{shortcutModifier()} I</kbd></button></div>
        <div className="plan-bar"><span className="plan-symbol"><Sparkles size={18}/></span><div><strong>{t.plan}</strong><span>설명과 규격을 묶음 제작 계획으로 정리합니다.</span></div><button className="button quiet" onClick={()=>{setPlanApproved(style.approved);setDialog('plan');}}>계획 작성<ChevronRight size={13}/></button></div>
        <div className="library-toolbar"><label className="search-input"><Search size={15}/><input ref={searchInput} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} aria-label={t.search}/>{query&&<button aria-label="검색 지우기" onClick={()=>setQuery('')}><X size={13}/></button>}<kbd>{shortcutModifier()} F</kbd></label><div className="toolbar-actions"><button className="button small" onClick={openGeneration}><Sparkles size={13}/>이미지 제작</button><button className="button small" onClick={()=>setDialog('model')}><Box size={13}/>3D 만들기</button><button className="button small" onClick={()=>setDialog('atlas')} disabled={imageAssets.length<1}><Layers size={13}/>아틀라스</button><label className="kind-filter"><ListFilter size={13}/><select value={kind} onChange={e=>setKind(e.target.value)} aria-label="에셋 유형 필터"><option value="all">전체 유형</option><option value="image">이미지</option><option value="model">3D 모델</option><option value="sprite">스프라이트</option><option value="texture">텍스처</option></select></label></div></div>
        <div className="asset-grid-wrap">
          {!snapshot?<div className="empty-state"><LoaderCircle className="spin" size={28}/><h2>로컬 프로젝트를 준비하고 있습니다.</h2></div>:filtered.length?<div className="asset-grid" role="list" aria-label="에셋 목록">{filtered.map(asset=>{const version=getVersion(asset);const thumb=snapshot?artifactUrl(snapshot,thumbnailArtifact(asset)):'';return <button key={asset.id} className={`asset-card ${selectedIds.includes(asset.id)?'selected':''}`} role="listitem" onClick={event=>selectAsset(asset,event.ctrlKey||event.metaKey||event.shiftKey)} onDoubleClick={()=>openAsset(asset)} title={`${asset.name} · 두 번 클릭해 열기`}><div className={`asset-thumbnail ${asset.kind==='model'?'model-thumbnail':''}`}><span className="selection-checkbox">{selectedIds.includes(asset.id)&&<Check size={11}/>}</span>{thumb?<img src={thumb} alt={asset.name} loading="lazy"/>:<Box size={56} strokeWidth={1}/>}<span className="asset-format">{asset.kind==='model'?'3D':outputArtifact(version)?.format.toUpperCase()??'PNG'}</span>{version?.source==='fixture'&&<span className="fixture-label">로컬 예제</span>}</div><div className="asset-card-info"><div><strong>{asset.name}</strong><span className="version-label">v{version?.number??1}</span></div><small>{asset.kind==='model'?`${asset.mesh?.triangles??'—'} triangles`: `${asset.width??'—'} × ${asset.height??'—'}`}<span>{KIND_LABELS[asset.kind]}</span></small></div></button>;})}</div>:<div className="empty-state"><FolderOpen size={36} strokeWidth={1.2}/><h2>{assets.length?'검색 결과가 없습니다.':'첫 번째 에셋을 가져오세요.'}</h2><p>{assets.length?'검색어나 필터를 바꿔 다시 찾아보세요.':isNative?'PNG, JPEG, WebP 원본을 가져오고 로컬 도구로 수정하세요.':'이미지 원본 또는 GLB를 가져오고 로컬 도구로 수정하세요.'}</p><div><button className="button" onClick={()=>void importAssets()}><Upload size={14}/>파일 가져오기</button>{!assets.length&&<button className="button quiet" onClick={()=>void run({action:'fixture',count:8},'결정론적으로 제작한 로컬 예제를 추가했습니다.')}><Package size={14}/>로컬 예제 추가</button>}</div></div>}
        </div>
        <div className="library-status"><span>{filtered.length}개 에셋{selectedIds.length?` / ${selectedIds.length}개 선택`:''}</span><span><MousePointer2 size={11}/>{shortcutModifier()} 클릭으로 여러 개 선택 · 두 번 클릭으로 열기</span></div>
      </>}

      {view==='canvas'&&<div className="canvas-workspace">
        <div className="canvas-toolbar"><div className="segmented"><IconButton title="선택 도구" active={brush==='select'} onClick={()=>setBrush('select')}><MousePointer2 size={15}/></IconButton><IconButton title="마스크 지우기" active={brush==='erase'} onClick={()=>{setBrush('erase');setMaskPoints([]);}} disabled={!selected||selected.kind==='model'}><Eraser size={15}/></IconButton><IconButton title="마스크 복원" active={brush==='restore'} onClick={()=>{setBrush('restore');setMaskPoints([]);}} disabled={!selected||selected.kind==='model'}><Paintbrush size={15}/></IconButton></div><span className="toolbar-divider"/><IconButton title="축소" onClick={()=>setZoom(z=>Math.max(.01,z*.85))}><Minus size={15}/></IconButton><button className="zoom-label" onClick={()=>setZoom(1)}>{Math.round(zoom*100)}%</button><IconButton title="확대" onClick={()=>setZoom(z=>Math.min(4,z*1.15))}><Plus size={15}/></IconButton><IconButton title="화면에 맞추기" onClick={fitImage}><Maximize2 size={15}/></IconButton><span className="toolbar-divider"/><IconButton title="픽셀 격자" active={grid} onClick={()=>setGrid(!grid)}><Grid2X2 size={15}/></IconButton><button className={`toolbar-text ${pivot?'active':''}`} onClick={()=>setPivot(!pivot)}>피벗</button><button className={`toolbar-text ${repeat?'active':''}`} onClick={()=>setRepeat(!repeat)}>반복</button><div className="toolbar-spacer"/>{selected&&selected.kind!=='model'&&<button className="button small" onClick={()=>setDialog('split')}><Layers size={13}/>시트 분할</button>}</div>
        {brush!=='select'&&<div className="brush-bar"><span>{brush==='erase'?'지울 영역':'복원할 영역'}을 이미지 위에 그리세요.</span><label>브러시 <input type="range" min="1" max="100" value={radius} onChange={e=>setRadius(Number(e.target.value))}/>{radius}px</label><button className="button small" disabled={!maskPoints.length||busy} onClick={()=>{applyImage({type:'mask',points:maskPoints,radius,mode:brush as 'erase'|'restore'});setMaskPoints([]);}}>새 버전에 적용</button><IconButton title="그린 마스크 지우기" onClick={()=>setMaskPoints([])}><RotateCcw size={14}/></IconButton></div>}
        <div className={`image-stage ${repeat?'repeat-stage':''}`}>
          {selected&&selected.kind!=='model'&&selectedUrl?<>{repeat?<div className="repeat-image checkerboard" style={{backgroundImage:`url("${selectedUrl}")`,backgroundSize:`${(selected.width??512)*zoom}px ${(selected.height??512)*zoom}px`}}/>:<div className={`image-object checkerboard ${brush!=='select'?'brush-cursor':''} ${project?.spec.pixelArt?'pixel-art':''}`} style={{width:(selected.width??512)*zoom,height:(selected.height??512)*zoom}} onPointerDown={event=>{if(brush==='select')return;event.currentTarget.setPointerCapture(event.pointerId);setDrawing(true);brushMoved.current=true;drawMask(event);}} onPointerMove={event=>{if(drawing)drawMask(event);}} onPointerUp={()=>{setDrawing(false);brushMoved.current=false;}} onPointerCancel={()=>setDrawing(false)}><img src={selectedUrl} alt={`${selected.name} 현재 버전`} draggable={false}/>{grid&&<div className="pixel-grid" style={{backgroundSize:`${16*zoom}px ${16*zoom}px`}}/>}{pivot&&<span className="pivot-marker" style={{left:`${(project?.spec.pivot[0]??.5)*100}%`,top:`${(project?.spec.pivot[1]??.5)*100}%`}}/>}{maskPoints.filter((_,i)=>i%2===0).map((point,i)=><span key={i} className={`mask-point ${brush}`} style={{left:point[0]*zoom,top:point[1]*zoom,width:radius*2*zoom,height:radius*2*zoom}}/>)}</div>}</>:<div className="empty-state"><FileImage size={36} strokeWidth={1.2}/><h2>2D 에셋을 선택하세요.</h2><p>라이브러리에서 이미지를 선택하면 이곳에서 수정할 수 있습니다.</p><button className="button" onClick={()=>setView('library')}>라이브러리 열기</button></div>}
        </div><div className="canvas-status"><span>{selected?.name??'선택 없음'}{selectedVersion&&` / v${selectedVersion.number}`}</span><span>{selected&&selected.kind!=='model'?`${selected.width} × ${selected.height} px / ${project?.spec.colorSpace??'sRGB'}`:'2D 캔버스'} · 원본 보존</span></div>
      </div>}

      {view==='model'&&<div className="model-workspace"><div className="canvas-toolbar"><Box size={15}/><span>{selected?.kind==='model'?selected.name:'3D 뷰포트'}</span><span className="toolbar-divider"/><button className={`toolbar-text ${wireframe?'active':''}`} onClick={()=>setWireframe(!wireframe)}>와이어프레임</button><div className="toolbar-spacer"/><button className="button small" onClick={()=>setDialog('model')}><Plus size={13}/>모델 제작</button></div><div className="model-viewer"><ModelViewport url={modelUrl} wireframe={wireframe}/>{selected?.kind==='model'&&<div className="viewport-stats"><span>Y-up / {selected.mesh?.unit??spec.unit}</span><span>{selected.mesh?.triangles??'—'} triangles</span><span>{selected.mesh?.dimensions.map(n=>n.toFixed(2)).join(' × ')??'치수 확인 필요'}</span></div>}</div><div className="canvas-status"><span>드래그: 회전 · 오른쪽 드래그: 이동 · 휠: 확대</span><span>{isNative?'GLB 실제 메시 미리보기':'브라우저 GLB 미리보기 / Blender 실행 아님'}</span></div></div>}

      {view==='compare'&&<div className="compare-workspace"><div className="canvas-toolbar"><Columns2 size={15}/><span>{selected?.name??'버전 비교'}</span><div className="toolbar-spacer"/><span className="toolbar-muted">각 수정본은 별도 버전으로 저장됩니다.</span></div>{selected&&selected.kind!=='model'?<><div className="compare-controls"><label>이전 버전 <select value={compareA} onChange={e=>setCompareA(e.target.value)}>{selected.versions.map(v=><option key={v.id} value={v.id}>v{v.number} · {new Date(v.createdAt).toLocaleDateString('ko-KR')}</option>)}</select></label><label>비교 버전 <select value={compareB} onChange={e=>setCompareB(e.target.value)}>{selected.versions.map(v=><option key={v.id} value={v.id}>v{v.number} · {new Date(v.createdAt).toLocaleDateString('ko-KR')}</option>)}</select></label></div><div className="compare-stage"><div className="compare-image checkerboard"><img src={imageSource(oldVersion)} alt="이전 버전"/><div className="compare-reveal" style={{clipPath:`inset(0 0 0 ${comparePosition}%)`}}><img src={imageSource(newVersion)} alt="비교 버전"/></div><div className="compare-divider" style={{left:`${comparePosition}%`}}><span><Columns2 size={16}/></span></div><span className="compare-label before">v{oldVersion?.number}</span><span className="compare-label after">v{newVersion?.number}</span><input aria-label="버전 비교 경계" className="compare-slider" type="range" min="0" max="100" value={comparePosition} onChange={e=>setComparePosition(Number(e.target.value))}/></div></div><div className="compare-notes"><div><strong>v{oldVersion?.number}</strong><span>{oldVersion?.prompt||'원본 파일'}</span></div><div><strong>v{newVersion?.number}</strong><span>{newVersion?.prompt||'원본 파일'}</span></div></div>{selected.versions.length===1&&<div className="inline-note">현재 원본 버전만 있습니다. 2D 캔버스에서 수정하면 비교할 새 버전이 만들어집니다.</div>}</>:<div className="empty-state"><Columns2 size={36}/><h2>비교할 2D 에셋을 선택하세요.</h2><button className="button" onClick={()=>setView('library')}>라이브러리 열기</button></div>}</div>}
    </main>

    <aside className="inspector" aria-label="선택 에셋과 제작 규격"><div className="inspector-tabs" role="tablist" aria-label="속성 패널"><button role="tab" aria-selected={inspector==='asset'} className={inspector==='asset'?'active':''} onClick={()=>setInspector('asset')}>에셋</button><button role="tab" aria-selected={inspector==='spec'} className={inspector==='spec'?'active':''} onClick={()=>{setSpec({...project?.spec??DEFAULT_SPEC});setInspector('spec');}}>규격</button><button role="tab" aria-selected={inspector==='style'} className={inspector==='style'?'active':''} onClick={()=>{setStyle({...project?.styleGuide??DEFAULT_STYLE});setInspector('style');}}>스타일</button><SlidersHorizontal size={14}/></div><div className="inspector-content">
      {inspector==='asset'&&<>{selected?<><div className="inspector-title"><span className="asset-type-icon">{selected.kind==='model'?<Box size={19}/>:<Image size={19}/>}</span><div><strong>{selected.name}</strong><small>{KIND_LABELS[selected.kind]} / v{selectedVersion?.number}</small></div></div><section className="inspector-section"><h2>기본 정보</h2><Field label="이름"><input value={assetName} onChange={e=>setAssetName(e.target.value)}/></Field><Field label="태그" hint="쉼표로 구분해 입력"><input value={assetTags} onChange={e=>setAssetTags(e.target.value)} placeholder="예: 아이템, 판타지"/></Field><button className="button inspector-save" disabled={busy||!assetName.trim()} onClick={()=>void run({action:'update',assetId:selected.id,name:assetName,tags:assetTags.split(',').map(v=>v.trim()).filter(Boolean)},'에셋 정보를 저장했습니다.')}><Check size={13}/>정보 저장</button><dl className="property-list"><div><dt>폴더</dt><dd>{selected.folder}</dd></div><div><dt>해상도 / 치수</dt><dd>{selected.kind==='model'?selected.mesh?.dimensions.map(n=>n.toFixed(2)).join(' × '):`${selected.width} × ${selected.height} px`}</dd></div><div><dt>파일 크기</dt><dd>{bytes(selectedVersion?.artifacts.reduce((n,a)=>n+a.bytes,0)??0)}</dd></div><div><dt>제작 경로</dt><dd>{selectedVersion?.source==='fixture'?'로컬 예제':selectedVersion?.source==='import'?'파일 가져오기':selectedVersion?.source==='procedural'?'절차적 제작':'외부 공급자'}</dd></div><div><dt>확인된 모델</dt><dd>{selectedVersion?.confirmedModel??'해당 없음 / 확인되지 않음'}</dd></div></dl></section>
        {selected.kind!=='model'&&<><section className="inspector-section"><h2>크기 조정 <span>새 버전</span></h2><div className="field-pair"><NumberField label="너비 px" value={resize.width} onChange={width=>setResize({...resize,width})} min={1}/><NumberField label="높이 px" value={resize.height} onChange={height=>setResize({...resize,height})} min={1}/></div><label className="check-row"><input type="checkbox" checked={spec.pixelArt} onChange={e=>setSpec({...spec,pixelArt:e.target.checked})}/>픽셀아트 / 최근접 보간</label><button className="button full" onClick={()=>applyImage({type:'resize',...resize,pixelArt:spec.pixelArt})} disabled={busy}>크기 조정</button></section><section className="inspector-section"><h2>자르기와 여백</h2><div className="field-pair"><NumberField label="X" value={crop.x} onChange={x=>setCrop({...crop,x})}/><NumberField label="Y" value={crop.y} onChange={y=>setCrop({...crop,y})}/></div><div className="field-pair"><NumberField label="너비" value={crop.width} onChange={width=>setCrop({...crop,width})} min={1}/><NumberField label="높이" value={crop.height} onChange={height=>setCrop({...crop,height})} min={1}/></div><div className="button-pair"><button className="button small" onClick={()=>applyImage({type:'crop',...crop})} disabled={busy}>자르기</button><button className="button small" onClick={()=>applyImage({type:'trim',padding:style.margin})} disabled={busy}>투명 여백 정리</button></div></section><section className="inspector-section"><h2>색상 변형</h2><label className="range-field"><span>색상 이동 <em>{color.hue}°</em></span><input type="range" min="-180" max="180" value={color.hue} onChange={e=>setColor({...color,hue:Number(e.target.value)})}/></label><label className="range-field"><span>채도 <em>{Math.round(color.saturation*100)}%</em></span><input type="range" min="0" max="2" step=".05" value={color.saturation} onChange={e=>setColor({...color,saturation:Number(e.target.value)})}/></label><button className="button full" onClick={()=>applyImage({type:'color',...color})} disabled={busy}>색상 적용</button></section><section className="inspector-section"><h2>배경 · 마스크 보정</h2><div className="color-control"><input aria-label="제거할 배경색" type="color" value={background.color} onChange={e=>setBackground({...background,color:e.target.value})}/><span>{background.color}</span><span>제거할 색</span></div><label className="range-field"><span>색상 허용 범위 <em>{background.tolerance}</em></span><input type="range" min="0" max="255" value={background.tolerance} onChange={e=>setBackground({...background,tolerance:Number(e.target.value)})}/></label><button className="button full" onClick={()=>applyImage({type:'background',...background})} disabled={busy}>선택 색 배경 제거</button><button className="text-button" onClick={()=>{setView('canvas');setBrush('erase');}}>브러시로 직접 보정<ChevronRight size={12}/></button><small className="muted-help">색상 기준 처리입니다. 경계가 복잡한 영역은 마스크 브러시로 보정하세요.</small></section></>}
        {isNative&&selected.kind!=='model'&&<section className="inspector-section"><h2>노멀맵 계산</h2><dl className="property-list"><div><dt>Base color</dt><dd>{spec.colorSpace}</dd></div><div><dt>Normal 방향</dt><dd>{spec.normalConvention}</dd></div><div><dt>데이터 색공간</dt><dd>linear · RGB</dd></div></dl><p className="muted-help">밝기를 높이로 가정한 휴리스틱 노멀맵입니다. 실제 표면의 물성 측정값을 나타내지는 않습니다.</p><button className="button full" disabled={busy} onClick={()=>void run({action:'material',assetId:selected.id,strength:2,directX:spec.normalConvention==='DirectX'},'휴리스틱 노멀맵 계산을 작업 큐에 추가했습니다.')}><Layers size={13}/>노멀맵 계산</button></section>}
        {selected.kind==='model'&&<section className="inspector-section"><h2>메시 정보</h2><dl className="property-list"><div><dt>정점</dt><dd>{selected.mesh?.vertices??'확인 필요'}</dd></div><div><dt>삼각형</dt><dd>{selected.mesh?.triangles??'확인 필요'}</dd></div><div><dt>단위</dt><dd>{selected.mesh?.unit??'m'}</dd></div><div><dt>GLB 축 방향</dt><dd>Y-up</dd></div></dl><button className="button full" onClick={()=>setView('model')}><Box size={14}/>3D 뷰포트에서 열기</button></section>}
        <section className="inspector-section"><h2>파일 검증{selectedVersion?.validation&&<span className={selectedVersion.validation.valid?'passed':'warning'}>{selectedVersion.validation.valid?'통과':'검토 필요'}</span>}</h2>{selectedVersion?.validation?selectedVersion.validation.checks.map((check,i)=><div className={`validation-check ${check.status}`} key={`${check.code}${i}`}>{check.status==='pass'?<Check size={12}/>:<AlertTriangle size={12}/>}<span>{check.message}</span></div>):<p className="muted-help">이 버전의 검증 보고서가 없습니다.</p>}</section><section className="inspector-section"><h2>버전 기록 <span>{selected.versions.length}</span></h2>{selected.versions.slice().reverse().map(v=><button className={`version-row ${v.id===selected.activeVersionId?'active':''}`} key={v.id} onClick={()=>{setCompareA(selected.versions[0].id);setCompareB(v.id);setView('compare');}}><span>v{v.number}</span><div><strong>{v.prompt||'원본 가져오기'}</strong><small>{new Date(v.createdAt).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small></div><Columns2 size={12}/></button>)}</section>
      </>:<div className="inspector-empty"><MousePointer2 size={26}/><strong>{t.noSelection}</strong><p>라이브러리에서 에셋을 선택하면 속성과 수정 도구가 표시됩니다.</p><button className="button small" onClick={()=>setInspector('spec')}>프로젝트 규격 보기</button></div>}</>}
      {inspector==='spec'&&<><div className="inspector-label"><SlidersHorizontal size={17}/><div><strong>{t.specification}</strong><small>프로젝트 전체에 적용</small></div></div><section className="inspector-section"><Field label="사용 분야"><select value={spec.domain} onChange={e=>setSpec({...spec,domain:e.target.value as AssetSpec['domain']})}>{Object.entries(DOMAIN_LABELS).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></Field><div className="field-pair"><NumberField label="기본 너비 px" value={spec.width} onChange={width=>setSpec({...spec,width})} min={1}/><NumberField label="기본 높이 px" value={spec.height} onChange={height=>setSpec({...spec,height})} min={1}/></div><div className="field-pair"><Field label="3D 단위"><select value={spec.unit} onChange={e=>setSpec({...spec,unit:e.target.value as AssetSpec['unit']})}><option>m</option><option>cm</option><option>mm</option></select></Field><Field label="축 방향"><select value={spec.axis} onChange={e=>setSpec({...spec,axis:e.target.value as AssetSpec['axis']})}><option>Y-up</option><option>Z-up</option></select></Field></div><div className="field-pair"><NumberField label="피벗 X" value={spec.pivot[0]} onChange={x=>setSpec({...spec,pivot:[x,spec.pivot[1]]})} max={1} step={.05}/><NumberField label="피벗 Y" value={spec.pivot[1]} onChange={y=>setSpec({...spec,pivot:[spec.pivot[0],y]})} max={1} step={.05}/></div><NumberField label="폴리곤 예산" value={spec.polygonBudget} onChange={polygonBudget=>setSpec({...spec,polygonBudget})} min={12} max={1000000} step={100}/><Field label="텍스처 색공간"><select value={spec.colorSpace} onChange={e=>setSpec({...spec,colorSpace:e.target.value as AssetSpec['colorSpace']})}><option>sRGB</option><option>linear</option></select></Field><Field label="노멀맵 방향"><select value={spec.normalConvention} onChange={e=>setSpec({...spec,normalConvention:e.target.value as AssetSpec['normalConvention']})}><option>OpenGL</option><option>DirectX</option></select></Field><label className="check-row"><input type="checkbox" checked={spec.pixelArt} onChange={e=>setSpec({...spec,pixelArt:e.target.checked})}/>픽셀아트 방식 사용</label><Field label="파일 이름 규칙"><input value={spec.naming} onChange={e=>setSpec({...spec,naming:e.target.value})}/></Field><Field label="대상 프로그램"><input value={spec.target} onChange={e=>setSpec({...spec,target:e.target.value})}/></Field><button className="button primary full" onClick={()=>void run({action:'update',spec},'제작 규격을 저장했습니다.')} disabled={busy}>규격 저장</button>{spec.domain==='architecture'&&<p className="muted-help">시각화용 메시 규격입니다. 제조 CAD, 공차, 안전 검토는 지원하지 않습니다.</p>}</section></>}
      {inspector==='style'&&<><div className="inspector-label"><Palette size={17}/><div><strong>{t.style}</strong><small>한 묶음의 제작 기준</small></div></div><section className="inspector-section"><Field label="스타일 이름"><input value={style.name} onChange={e=>setStyle({...style,name:e.target.value})}/></Field><span className="field-label">팔레트</span><div className="style-palette">{style.palette.map((c,i)=><label key={i} title={c}><input type="color" value={c} aria-label={`팔레트 색상 ${i+1}`} onChange={e=>setStyle({...style,palette:style.palette.map((p,n)=>n===i?e.target.value:p)})}/><span>{c}</span></label>)}</div><NumberField label="선 두께 px" value={style.lineWeight} onChange={lineWeight=>setStyle({...style,lineWeight})} max={20} step={.5}/><Field label="카메라"><input value={style.camera} onChange={e=>setStyle({...style,camera:e.target.value})}/></Field><Field label="조명"><input value={style.lighting} onChange={e=>setStyle({...style,lighting:e.target.value})}/></Field><Field label="디테일"><textarea rows={3} value={style.detail} onChange={e=>setStyle({...style,detail:e.target.value})}/></Field><NumberField label="투명 여백 px" value={style.margin} onChange={margin=>setStyle({...style,margin})} max={512}/><div className="reference-block"><span>기준 에셋</span>{style.referenceAssetIds.length?<div className="reference-thumbnails">{assets.filter(a=>style.referenceAssetIds.includes(a.id)).map(a=><img key={a.id} src={snapshot?artifactUrl(snapshot,thumbnailArtifact(a)):''} alt={a.name}/>)}</div>:<p>선택한 에셋을 스타일 참조로 지정할 수 있습니다.</p>}<button className="button small" disabled={!selectedIds.length} onClick={()=>setStyle({...style,referenceAssetIds:[...selectedIds]})}><Plus size={12}/>선택 에셋을 참조로</button></div><label className="check-row approval"><input type="checkbox" checked={style.approved} onChange={e=>setStyle({...style,approved:e.target.checked})}/><span>이 스타일을 제작 기준으로 승인</span></label><button className="button primary full" onClick={()=>void run({action:'update',styleGuide:style},'스타일 가이드를 저장했습니다.')} disabled={busy}>스타일 저장</button><small className="muted-help">색상·카메라·참조를 전달할 기준입니다. 캐릭터 동일성과 프레임 연속성은 별도 검토가 필요합니다.</small></section></>}
    </div></aside>

    <section className={`queue-panel ${queueOpen?'':'collapsed'}`} aria-label="작업 큐"><div className="queue-heading"><button className="queue-toggle" onClick={()=>setQueueOpen(!queueOpen)}><ChevronDown size={13} className={queueOpen?'':'rotated'}/><Layers size={15}/>{t.queue}<span className="small-count">{jobs.length}</span></button><div className="queue-filter"><button className={queueFilter==='all'?'active':''} onClick={()=>setQueueFilter('all')}>전체</button><button className={queueFilter==='active'?'active':''} onClick={()=>setQueueFilter('active')}>진행 중{activeJobs.length>0&&` ${activeJobs.length}`}</button><button className={queueFilter==='failed'?'active':''} onClick={()=>setQueueFilter('failed')}>실패</button><button className={queueFilter==='succeeded'?'active':''} onClick={()=>setQueueFilter('succeeded')}>완료</button></div><span className="queue-summary">{isNative?'Rust 로컬 큐':'브라우저 로컬 큐'}<span className="connection-dot"/>외부 생성 별도 확인</span><IconButton title="작업 상태 새로고침" onClick={()=>void run({action:'snapshot'})}><RefreshCw size={13}/></IconButton></div>{queueOpen&&<div className="queue-table-wrap">{filteredJobs.length?<table className="queue-table"><thead><tr><th>작업</th><th>상태</th><th>현재 단계</th><th>자원</th><th>시작</th><th>작업 관리</th></tr></thead><tbody>{filteredJobs.map(job=><tr key={job.id}><td><button className="job-name" onClick={()=>{setJobDetail(job);setDialog('job');}}>{job.kind.includes('model')?<Box size={13}/>:<FileImage size={13}/>}<span>{job.label}</span></button></td><td><span className={`job-status ${job.status}`}><StatusIcon status={job.status}/>{JOB_LABELS[job.status]??job.status}</span></td><td><span className={job.error?'job-error':''} title={job.error??job.progress.stage}>{job.error??job.progress.stage}{job.progress.completed!=null&&job.progress.total!=null&&` (${job.progress.completed}/${job.progress.total})`}</span></td><td>{job.resource==='blender'?'Blender':job.resource==='cpu'?'CPU':'외부 공급자'}</td><td>{formatTime(job.startedAt)}</td><td><div className="job-actions">{ACTIVE.has(job.status)&&<IconButton title={`${job.label} 취소`} onClick={()=>void run({action:'cancel',jobId:job.id},'작업 취소를 요청했습니다. 외부 처리 취소는 공급자 확인 뒤 반영됩니다.')}><X size={13}/></IconButton>}{['failed','cancelled','succeeded'].includes(job.status)&&<IconButton title={`${job.label} ${job.resource==='external'?'새 이미지 요청 (사용량 발생 가능)':'재실행'}`} onClick={()=>void run({action:'rerun',jobId:job.id},job.resource==='external'?'새 이미지 요청을 큐에 추가했습니다. 구독 사용량이 발생할 수 있습니다.':'선택한 작업을 다시 실행합니다.')}><RotateCcw size={13}/></IconButton>}<IconButton title={`${job.label} 상세 정보`} onClick={()=>{setJobDetail(job);setDialog('job');}}><MoreHorizontal size={14}/></IconButton></div></td></tr>)}</tbody></table>:<div className="queue-empty"><CheckCircle2 size={18}/><div><strong>{queueFilter==='all'?'작업 공간이 준비되었습니다.':'이 상태의 작업이 없습니다.'}</strong><span>{queueFilter==='all'?'이미지 수정이나 모델 제작을 시작하면 작업 단계와 결과가 여기에 표시됩니다.':'다른 필터를 선택해 작업을 확인하세요.'}</span></div></div>}</div>}</section>
    <footer className="statusbar"><span><span className="connection-dot"/>로컬 저장 · 원본 보존</span><span>{isNative?env?.blenderVersion?`Blender ${env.blenderVersion}`:'Blender 설치 확인 필요':'브라우저 미리보기 / 네이티브 기능은 데스크톱에서 검증'}<button onClick={()=>setLocale(locale==='ko'?'en':'ko')}>{locale==='ko'?'한국어':'English'}<ChevronDown size={10}/></button></span></footer>

    {(error||notice)&&<div className={`notification ${error?'error':''}`} role={error?'alert':'status'}>{error?<AlertTriangle size={17}/>:<CheckCircle2 size={17}/>}<span>{error||notice}</span><button aria-label="알림 닫기" onClick={()=>{setError('');setNotice('');}}><X size={15}/></button></div>}
    {dragging&&<div className="drop-overlay"><Upload size={42}/><strong>원본 파일을 여기에 놓으세요.</strong><span>{isNative?'PNG · JPEG · WebP / 기존 원본은 보존됩니다.':'이미지 · GLB · 프로젝트 ZIP / 기존 원본은 보존됩니다.'}</span></div>}

    {dialog&&<div className="dialog-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setDialog(null);}}><section className={`dialog dialog-${dialog}`} role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div className="dialog-header"><div><h2 id="dialog-title">{dialog==='project'?'새 프로젝트':dialog==='model'?'절차적 3D 모델 제작':dialog==='atlas'?'스프라이트 아틀라스':dialog==='split'?'스프라이트시트 분할':dialog==='export'?'에셋 묶음 내보내기':dialog==='plan'?'제작 계획 작성':dialog==='generate'?'GPT Image2 이미지 제작':dialog==='provider'?'이미지 생성 연동 상태':dialog==='environment'?'환경 및 지원 정보':dialog==='update'?'앱 업데이트':dialog==='guide'?'사용 가이드':'작업 상세'}</h2><p>{dialog==='model'?'치수와 재질을 지정해 실제 메시를 만듭니다.':dialog==='export'?'결과 파일과 독립적으로 읽을 수 있는 manifest를 함께 저장합니다.':dialog==='plan'?'로컬 규칙으로 제작 항목과 규격을 정리합니다.':dialog==='generate'?'공식 런타임 연결을 확인하고 이미지 요청을 직접 제출합니다.':dialog==='project'?'원본, 수정본, 작업 이력을 프로젝트에 저장합니다.':''}</p></div><IconButton title="대화상자 닫기" onClick={()=>setDialog(null)}><X size={18}/></IconButton></div>
      {dialog==='project'&&<form onSubmit={newProject}><Field label="프로젝트 이름"><input value={projectName} onChange={e=>setProjectName(e.target.value)} required maxLength={100}/></Field><div className="inline-note"><Folder size={17}/>{isNative?'다음 단계에서 빈 저장 폴더를 선택합니다. 기존 원본을 덮어쓰지 않습니다.':'브라우저 미리보기 프로젝트는 이 기기의 IndexedDB에 저장됩니다. 결과물은 ZIP 파일로 내보낼 수 있습니다.'}</div><div className="dialog-actions"><button className="button" type="button" onClick={()=>setDialog(null)}>취소</button><button className="button primary" type="submit" disabled={busy||!projectName.trim()}><FilePlus2 size={14}/>프로젝트 만들기</button></div></form>}
      {dialog==='model'&&<form onSubmit={createModels}><div className="model-template-list">{([{id:'crate',name:'상자 · 컨테이너',description:'패널과 프레임이 있는 상자'},{id:'table',name:'테이블',description:'상판과 네 개의 다리'},{id:'shelf',name:'선반',description:'측면 프레임과 선반'}] as const).map(item=><button key={item.id} type="button" className={model.template===item.id?'selected':''} onClick={()=>setModel({...model,template:item.id,name:item.id==='crate'?'나무 상자':item.id==='table'?'테이블':'선반'})}><Box size={23}/><strong>{item.name}</strong><small>{item.description}</small>{model.template===item.id&&<Check size={13}/>}</button>)}</div><Field label="모델 이름"><input value={model.name} onChange={e=>setModel({...model,name:e.target.value})} required/></Field><div className="field-triple"><NumberField label={`너비 (${spec.unit})`} value={model.width} onChange={width=>setModel({...model,width})} min={.03/UNIT_FACTORS[spec.unit]} max={100/UNIT_FACTORS[spec.unit]} step="any"/><NumberField label={`깊이 (${spec.unit})`} value={model.depth} onChange={depth=>setModel({...model,depth})} min={.03/UNIT_FACTORS[spec.unit]} max={100/UNIT_FACTORS[spec.unit]} step="any"/><NumberField label={`높이 (${spec.unit})`} value={model.height} onChange={height=>setModel({...model,height})} min={.03/UNIT_FACTORS[spec.unit]} max={100/UNIT_FACTORS[spec.unit]} step="any"/></div><div className="field-pair"><NumberField label={`모서리 베벨 (${spec.unit})`} value={model.bevel} onChange={bevel=>setModel({...model,bevel})} min={0} max={.25/UNIT_FACTORS[spec.unit]} step="any"/><NumberField label="제작 수" value={modelCount} onChange={setModelCount} min={1} max={24}/></div><div className="color-control model-color"><input type="color" value={model.color} onChange={e=>setModel({...model,color:e.target.value})} aria-label="모델 재질 색상"/><span>{model.color}</span><span>Base color</span><div className="mini-palette">{style.palette.map(c=><button key={c} type="button" aria-label={`재질 색상 ${c}`} style={{background:c}} onClick={()=>setModel({...model,color:c})}/>)}</div></div><div className="inline-note"><Box size={17}/>{isNative?env?.blenderPath?'고정된 Blender 템플릿으로 제작합니다. GLB는 미터 · Y-up, Blender 원본은 Z-up입니다.':'Blender가 없으면 작업 큐에 원인을 표시합니다. 환경 정보에서 설치 상태를 확인하세요.':'브라우저에서는 Three.js로 GLB 메시를 제작합니다. Blender 원본과 네이티브 작업 검증은 데스크톱에서 가능합니다.'}</div><div className="dialog-actions"><button className="button" type="button" onClick={()=>setDialog(null)}>취소</button><button className="button primary" disabled={busy} type="submit"><Play size={13}/>모델 제작 시작</button></div></form>}
      {dialog==='atlas'&&<form onSubmit={async event=>{event.preventDefault();if(!imageAssets.length)return;const next=await run({action:'atlas',assetIds:imageAssets.map(a=>a.id),options:atlas,frameRate:spriteFrameRate},'아틀라스와 프레임 메타데이터 제작을 시작했습니다.');if(next)setDialog(null);}}><p className="dialog-copy">선택한 2D 에셋 {imageAssets.length}개를 하나의 PNG와 JSON 좌표 정보로 묶습니다.</p><div className="selected-asset-strip">{imageAssets.slice(0,6).map(a=><img key={a.id} src={snapshot?artifactUrl(snapshot,thumbnailArtifact(a)):''} alt={a.name}/>)}</div><div className="field-pair"><NumberField label="아틀라스 너비 px" value={atlas.width} onChange={width=>setAtlas({...atlas,width})} min={64} max={8192}/><NumberField label="아틀라스 높이 px" value={atlas.height} onChange={height=>setAtlas({...atlas,height})} min={64} max={8192}/></div><div className="field-pair"><NumberField label="프레임 사이 여백 px" value={atlas.padding} onChange={padding=>setAtlas({...atlas,padding})} min={0} max={64}/><NumberField label="재생 속도 fps" value={spriteFrameRate} onChange={setSpriteFrameRate} min={1} max={240} step="any"/></div>{!imageAssets.length&&<div className="inline-note warning">먼저 라이브러리에서 2D 에셋을 선택하세요. {shortcutModifier()} 클릭으로 여러 개를 선택합니다.</div>}<div className="dialog-actions"><button type="button" className="button" onClick={()=>setDialog(null)}>취소</button><button className="button primary" disabled={busy||!imageAssets.length} type="submit"><Layers size={14}/>아틀라스 제작</button></div></form>}
      {dialog==='split'&&<form onSubmit={async event=>{event.preventDefault();if(!selected)return;const next=await run({action:'split',assetId:selected.id,frameWidth:split.width,frameHeight:split.height,frameRate:spriteFrameRate},'시트를 실제 프레임 파일로 분할합니다.');if(next)setDialog(null);}}><p className="dialog-copy">{selected?.name} · {selected?.width} × {selected?.height} px</p><div className="field-pair"><NumberField label="프레임 너비 px" value={split.width} onChange={width=>setSplit({...split,width})} min={1} max={8192}/><NumberField label="프레임 높이 px" value={split.height} onChange={height=>setSplit({...split,height})} min={1} max={8192}/></div><NumberField label="재생 속도 fps" value={spriteFrameRate} onChange={setSpriteFrameRate} min={1} max={240} step="any"/><div className="inline-note">행 우선 순서로 분할합니다. 시트 크기가 프레임 크기로 나누어져야 합니다. 피벗은 프로젝트 규격을 사용합니다.</div><div className="dialog-actions"><button className="button" type="button" onClick={()=>setDialog(null)}>취소</button><button className="button primary" type="submit" disabled={busy||!selected}><Layers size={14}/>프레임 분할</button></div></form>}
      {dialog==='export'&&<form onSubmit={exportAssets}><div className="export-summary"><Package size={29}/><div><strong>{project?.name??'프로젝트'}</strong><span>{selectedIds.length?`선택한 에셋 ${selectedIds.length}개`:`전체 에셋 ${assets.length}개`} / 결과 파일 + manifest</span></div></div><Field label="대상 프로그램 프리셋"><select value={exportPreset} onChange={e=>{setExportPreset(e.target.value);const p=EXPORT_PRESETS.find(p=>p.id===e.target.value);if(p&&!p.formats.includes(exportFormat))setExportFormat('png');}}>{EXPORT_PRESETS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="이미지 파일 형식"><select value={exportFormat} onChange={e=>setExportFormat(e.target.value)}><option value="png">PNG · 투명도 보존</option><option value="webp">WebP · 투명도 보존</option><option value="jpeg">JPEG · 투명 영역 흰색</option></select></Field><div className="export-includes"><div><Check size={13}/>실제 이미지 / GLB 결과물</div><div><Check size={13}/>규격 · 버전 · 파일 해시 manifest</div><div><Check size={13}/>아틀라스 좌표 등 JSON 메타데이터</div></div><div className="inline-note">{isNative?'선택한 폴더 안에 새로운 묶음으로 저장합니다. 기존 원본은 보존됩니다.':'ZIP 파일로 다운로드됩니다. 브라우저 저장소와 독립적으로 결과물을 보관하세요.'}</div><div className="dialog-actions"><button className="button" type="button" onClick={()=>setDialog(null)}>취소</button><button className="button primary" type="submit" disabled={busy||!assets.length}><Download size={14}/>묶음 내보내기</button></div></form>}
      {dialog==='generate'&&<form onSubmit={createImages}>
        <Field label="이미지 설명"><textarea rows={4} value={generationPrompt} onChange={e=>setGenerationPrompt(e.target.value)} placeholder="예: 금속 프레임과 맑은 유리가 있는 판타지 회복 물약 아이콘" required/></Field>
        <div className="generation-fields"><Field label="이미지 이름 (선택)" hint="최대 80자"><input value={generationName} onChange={e=>setGenerationName(e.target.value)} placeholder="이름을 지정하지 않으면 자동 이름 사용" maxLength={80}/></Field><NumberField label="이미지 수" value={generationCount} onChange={setGenerationCount} min={1} max={20}/></div>
        <div className="plan-spec-line"><Palette size={15}/><span>{style.name} · {spec.width} × {spec.height}px · {DOMAIN_LABELS[spec.domain]}</span><div className="mini-palette">{style.palette.map(c=><span key={c} style={{background:c}}/>)}</div></div>
        <label className="check-row approval"><input type="checkbox" checked={generationApproved} onChange={e=>setGenerationApproved(e.target.checked)}/>현재 규격과 스타일을 제작 기준으로 승인합니다.</label>
        {providerPanel}
        <div className="inline-note"><Sparkles size={17}/><span>{isNative?'제출한 설명과 승인한 제작 기준을 공식 런타임에 전달합니다. 이미지마다 별도 작업을 생성하며 구독 사용량이 발생할 수 있습니다. 정확한 크기·투명도·스타일 일치 여부는 결과 파일에서 검토하세요.':'브라우저 미리보기에서는 이미지 제작 요청이 제출되지 않습니다. 데스크톱 앱에서 연결을 확인하세요.'}</span></div>
        <div className="dialog-actions"><button className="button" type="button" onClick={()=>setDialog(null)}>닫기</button><button className="button primary" type="submit" disabled={busy||providerChecking!==null||!isNative||!connection?.ready||!generationApproved||!generationPrompt.trim()||!Number.isInteger(generationCount)||generationCount<1||generationCount>20}><Sparkles size={14}/>{busy?'요청 제출 중':'이미지 요청 제출'}</button></div>
      </form>}
      {dialog==='plan'&&<>
        <Field label="어떤 에셋 묶음이 필요한가요?"><textarea rows={4} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="예: 같은 스타일의 판타지 아이템 아이콘 20개와 상자 3D 모델 3개"/></Field>
        <div className="plan-preview"><div className="plan-preview-heading"><strong>정리된 제작 항목</strong><span>로컬 규칙 해석</span></div>
          {plan.models>0&&<div><Box size={18}/><span><strong>{plan.template==='crate'?'상자 · 컨테이너':plan.template==='table'?'테이블':'선반'} {plan.models}개</strong><small>절차적 메시 · 프로젝트 치수와 스타일 적용</small></span><span className="status-tag ready">로컬 제작</span></div>}
          {plan.images>0&&<div><Image size={18}/><span><strong>이미지 {plan.images}개</strong><small>{isNative?'GPT Image2 공식 런타임 · 이미지마다 별도 작업':'브라우저에서는 이미지 요청을 제출하지 않습니다.'}</small></span><span className={`status-tag ${isNative&&connection?.ready?'ready':'blocked'}`}>{!isNative?'데스크톱 전용':connection?.ready?'연결 준비':'연결 확인 필요'}</span></div>}
          {!plan.images&&!plan.models&&<p>상자, 테이블, 선반 또는 이미지와 필요한 개수를 입력하세요.</p>}
        </div>
        <div className="plan-spec-line"><Palette size={15}/><span>{style.name} · {spec.width} × {spec.height}px · {DOMAIN_LABELS[spec.domain]}</span><div className="mini-palette">{style.palette.map(c=><span key={c} style={{background:c}}/>)}</div></div>
        <label className="check-row approval"><input type="checkbox" checked={planApproved} onChange={e=>setPlanApproved(e.target.checked)}/>현재 규격과 스타일을 제작 기준으로 승인합니다.</label>
        {plan.images>0&&providerPanel}
        <div className="inline-note">설명에서 템플릿과 개수를 추출합니다. 3D 항목은 로컬 절차적 메시를 만듭니다. {isNative&&plan.images>0?'제출 시 이미지 설명과 승인한 기준을 공식 런타임에 전달하며 구독 사용량이 발생할 수 있습니다.':!isNative&&plan.images>0?'브라우저에서는 표시된 로컬 모델 항목만 제작합니다.':''} 한 계획은 모델 24개, 이미지 20개까지입니다.</div>
        <div className="dialog-actions"><button className="button" onClick={()=>setDialog('provider')}>공급자 상태</button><button className="button primary" onClick={()=>void runPlan()} disabled={busy||providerChecking!==null||!prompt.trim()||!planApproved||(!plan.models&&!plan.images)||plan.models>24||plan.images>20||(!!plan.images&&isNative&&!connection?.ready)||(!isNative&&!plan.models)}><Play size={13}/>{!isNative?'로컬 제작 시작':'제작 요청 제출'}</button></div>
      </>}
      {dialog==='guide'&&<><UsageGuide/><div className="dialog-actions"><button className="button" onClick={()=>setDialog('update')}>앱 업데이트</button><button className="button primary" onClick={()=>setDialog(null)}>닫기</button></div></>}
      {dialog==='update'&&<AppUpdatePanel updater={updater} workBlocked={updateWorkBlocked}/>}
      {dialog==='provider'&&<div className="provider-content">
        {providerPanel}
        <p className="muted-help">기존 이미지 가져오기와 로컬 후처리도 사용할 수 있습니다. 앱 코어의 오픈소스 라이선스와 외부 서비스 이용 조건은 별개입니다. 생성·편집·참조 이미지·원격 취소의 지원 범위는 실제 결과와 공식 응답을 통해 기록합니다.</p>
        <div className="dialog-actions"><button className="button" onClick={()=>{setDialog(null);void importAssets();}}><Upload size={14}/>기존 이미지 가져오기</button><button className="button primary" onClick={openGeneration}><Sparkles size={14}/>이미지 제작</button><button className="button" onClick={()=>setDialog(null)}>확인</button></div>
      </div>}
      {dialog==='environment'&&<><div className="environment-mark"><span className="brand-symbol"><Layers size={28}/></span><div><h3>Asset Studio</h3><p>local-first asset workbench · {updater.status.currentVersion}</p></div></div><dl className="property-list environment-list"><div><dt>실행 환경</dt><dd>{isNative?'Tauri 데스크톱':'브라우저 미리보기'}</dd></div><div><dt>플랫폼</dt><dd>{env?.platform??'확인 중'}</dd></div><div><dt>프로젝트 저장</dt><dd>{isNative?'로컬 폴더 + SQLite':'이 기기의 IndexedDB'}</dd></div><div><dt>Blender</dt><dd>{env?.blenderVersion??'설치 확인 필요'}</dd></div><div><dt>프로젝트 위치</dt><dd className="breakable">{snapshot?.root??'확인 중'}</dd></div><div><dt>원격 전송</dt><dd>로컬 작업은 외부 전송 없음</dd></div></dl><div className="inline-note">Windows · macOS 데스크톱을 목표로 합니다. 현재 기기의 빌드·실행 검증과 다른 플랫폼 지원 검증은 별개로 기록됩니다.</div><div className="keyboard-help"><span>{shortcutModifier()} I <em>파일 가져오기</em></span><span>{shortcutModifier()} E <em>묶음 내보내기</em></span><span>{shortcutModifier()} F <em>검색</em></span><span>{shortcutModifier()} A <em>표시된 에셋 전체 선택</em></span><span>Esc <em>대화상자 닫기</em></span></div><div className="dialog-actions"><button className="button primary" onClick={()=>setDialog(null)}>확인</button></div></>}
      {dialog==='job'&&jobDetail&&<><div className="job-detail-title"><StatusIcon status={jobDetail.status}/><strong>{jobDetail.label}</strong><span className={`job-status ${jobDetail.status}`}>{JOB_LABELS[jobDetail.status]}</span></div><dl className="property-list environment-list"><div><dt>종류</dt><dd>{jobDetail.kind}</dd></div><div><dt>현재 단계</dt><dd>{jobDetail.progress.stage}</dd></div><div><dt>자원</dt><dd>{jobDetail.resource}</dd></div><div><dt>시도 횟수</dt><dd>{jobDetail.attempts}</dd></div><div><dt>시작</dt><dd>{formatTime(jobDetail.startedAt)}</dd></div><div><dt>완료</dt><dd>{formatTime(jobDetail.finishedAt)}</dd></div><div><dt>선행 작업</dt><dd>{jobDetail.dependencies.length||'없음'}</dd></div></dl>{jobDetail.error&&<div className="job-error-detail"><AlertTriangle size={16}/><p>{jobDetail.error}</p></div>}<details className="job-parameters"><summary>실행 매개변수</summary><pre>{JSON.stringify(jobDetail.payload,null,2)}</pre></details><div className="dialog-actions"><button className="button" onClick={()=>setDialog(null)}>닫기</button>{['failed','cancelled','succeeded'].includes(jobDetail.status)&&<button className="button primary" onClick={()=>{void run({action:'rerun',jobId:jobDetail.id},jobDetail.resource==='external'?'새 이미지 요청을 큐에 추가했습니다. 구독 사용량이 발생할 수 있습니다.':'이 작업만 다시 실행합니다.');setDialog(null);}}><RotateCcw size={14}/>{jobDetail.resource==='external'?'새 이미지 요청 제출':'이 작업 재실행'}</button>}</div></>}
      {dialog==='job'&&isNative&&jobDetail?.status==='succeeded'&&jobDetail.cacheKey&&<section className="inspector-section"><p className="muted-help">작업 설정과 파일 해시를 확인한 저장 결과를 선택합니다. 새 변형을 만들려면 재실행을 사용하세요.</p><button className="button full" disabled={busy} onClick={()=>{void run({action:'reuse',jobId:jobDetail.id},'해시를 검증한 저장 결과를 재사용했습니다.');setDialog(null);}}><Copy size={14}/>저장 결과 재사용</button></section>}
      {dialog==='job'&&jobDetail?.resource==='external'&&<div className="inline-note external-job-note"><AlertTriangle size={16}/><span>재실행은 새로운 이미지 요청이며 구독 사용량이 발생할 수 있습니다. 실행 중 취소한 외부 작업은 공급자가 종료를 확인할 때까지 결과 불명으로 남을 수 있습니다. 결과 불명 작업은 자동으로 다시 제출하지 않습니다.</span></div>}
    </section></div>}
  </div>;
}





