import { ArrowDownToLine, ArrowUpRight } from 'lucide-react';
import { assets } from './state';
import { sourceUrl } from '../content';
import SiteFooterLinks from '../SiteFooterLinks';

export default function WorkshopStory() {
  return <div className="project-overview" lang="en">
    <a className="skip-link" href="#story-main">Skip to content</a>
    <header className="overview-header page-width"><a className="wordmark" href="/">Treeset</a><nav aria-label="Example navigation"><a href="/play/workshop/en/">Play the example</a><a href="/about/">Project overview</a><a href="/play/workshop/" lang="ko">한국어</a></nav></header>
    <main id="story-main">
      <section className="workflow-case-hero page-width"><p className="overview-product">Asset Studio / developer example</p><h1>From three GLBs<br />to a playable workshop.</h1><p className="overview-lead">A small browser example turns separately produced local props into a scene you can walk through, rearrange and save. Try it before installing Asset Studio.</p><p className="workflow-case-status">Published example · October 8, 2026 · JEONG WOOCHEOL</p><div className="overview-actions"><a className="button button-primary" href="/play/workshop/en/">Play the workshop</a><a className="button button-secondary" href="/examples/workshop-starter.zip" download><ArrowDownToLine size={18} aria-hidden="true" />Download the example files</a></div></section>
      <section className="overview-section page-width"><div className="overview-section-heading"><h2>Three props, one small task.</h2><p>A robot brings three glowing cells to the workbench. Each delivery lights a prop. Afterward, choose a prop, move it to a new position and save the scene layout.</p></div><ol className="overview-workflow"><li><h3>Produce individual files</h3><p>The Windows local workflow produced a storage crate, workbench and shelf with separate GLB, editable Blender source and thumbnail files. Each source was reopened independently.</p></li><li><h3>Use the actual models</h3><p>The example checks the bytes and SHA-256 of each GLB before displaying it. The models keep their metre scale and Y-up orientation; collision bounds use their footprints.</p></li><li><h3>Keep an editable scene</h3><p>Arrange the props on the floor, rotate them and save a new JSON file. Reopening that file restores the layout. The original GLB and Blender files stay unchanged.</p></li></ol><div className="overview-proof-links"><a className="text-link" href="/about/#local-workflow">Native production record<ArrowUpRight size={17} aria-hidden="true" /></a><a className="text-link" href={`${sourceUrl}/tree/master/examples/procedural`}>Original procedural examples<ArrowUpRight size={17} aria-hidden="true" /></a><a className="text-link" href={`${sourceUrl}/tree/master/apps/site/src/workshop`}>Read the web example source<ArrowUpRight size={17} aria-hidden="true" /></a></div></section>
      <section className="overview-section page-width"><div className="overview-section-heading"><h2>Inspect what goes into the scene.</h2><p>These three actual GLBs total 242,460 bytes and 3,348 triangles. They use simple PBR materials and have no image textures. These counts describe the props, not the entire scene or a measured frame rate.</p></div><div className="overview-local-outputs">{assets.map(asset => <article key={asset.id}><img src={`/examples/local-prop-kit/${asset.id}/thumbnail.png`} width="512" height="512" loading="lazy" alt={`Actual Blender render of ${asset.english}`} /><h3>{asset.english}</h3><p>{asset.triangles.toLocaleString('en-US')} triangles · {asset.bytes.toLocaleString('en-US')} bytes</p><div className="overview-proof-links"><a className="text-link" href={`/examples/local-prop-kit/${asset.id}/model.glb`} download>GLB</a><a className="text-link" href={`/examples/local-prop-kit/${asset.id}/source.blend`} download>Blender source</a></div></article>)}</div><div className="overview-proof-links"><a className="text-link" href="/examples/workshop/scene.json" download>Default scene JSON</a><a className="text-link" href="/examples/workshop/manifest.json" download>File inventory and SHA-256</a><a className="text-link" href="/examples/workshop/README.md">Example instructions</a></div></section>
      <section className="overview-section page-width"><div className="overview-section-heading"><h2>The scope of this example.</h2><p>This is a developer-built web example using existing local procedural outputs. It introduces a real way to try the assets and inspect their files.</p></div><div className="overview-proof-list"><article><h3>What you can try</h3><p>Keyboard and on-screen movement, pickup and delivery, solid prop collision, layout changes, scene JSON save/reopen and PNG capture. The example loads files from this website and stores layouts in your browser.</p></article><article><h3>How Claude fits</h3><p>The separate Claude Code planning source prototype turns creator-approved briefs into asset instructions and review checks. Live Claude execution remains pending. This workshop did not call Claude or an image-generation provider.</p><a className="text-link" href="/workflows/claude-asset-brief/">Inspect the Claude prototype<ArrowUpRight size={17} aria-hidden="true" /></a></article><article><h3>Platform and quality boundaries</h3><p>Browser gameplay does not establish new Windows or macOS desktop support. This example does not demonstrate image-to-3D, texture baking, rigging, animation production or game-engine import beyond this Three.js scene.</p><a className="text-link" href={`${sourceUrl}/releases/tag/v0.1.13`}>Published desktop releases<ArrowUpRight size={17} aria-hidden="true" /></a></article><article><h3>Feedback and development</h3><p>This is an initial developer example. We have no external user feedback or verified Claude usage to report yet. Try the workshop and share the task, platform and result when reporting an issue.</p><a className="text-link" href={`${sourceUrl}/issues/new`}>Open an issue<ArrowUpRight size={17} aria-hidden="true" /></a></article></div></section>
    </main>
    <footer className="overview-footer page-width"><p>Treeset / Asset Studio · JEONG WOOCHEOL</p><nav><a href="/play/workshop/en/">Play the example</a><a href="/about/">Project overview</a><SiteFooterLinks language="en" /><a href={sourceUrl}>GitHub</a><a href="mailto:oocheol@treeset.win">oocheol@treeset.win</a></nav></footer>
  </div>;
}
